name: Deploy React client to GitHub Pages

on:
    push:
        branches:
            - main # Trigger on commits to the main branch
    pull_request:
        branches:
            - main # Trigger on PRs targeting the main branch

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@v4

            # Set up Node.js 20.x (as per your specified version)
            - name: Set up Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: '20.17.x' # Using Node.js version 20.x

            # Navigate to the client folder
            - name: Install dependencies for client
              run: |
                  cd client
                  npm ci

            # Build the React project in client folder
            - name: Build React project
              run: |
                  cd client
                  npm run build

            # Deploy to GitHub Pages
            - name: 🚀 Deploy to GitHub Pages 🚀
              if: github.ref == 'refs/heads/main'
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .client/dist
