name: Deploy React client to GitHub Pages

on:
    push:
        branches:
            - main # Trigger on commits to the main branch
    pull_request:
        branches:
            - main # Trigger on PRs targeting the main branch

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@v4

            # Set up Node.js 20.x (as per your specified version)
            - name: Set up Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x' # Using Node.js version 20.x
                  cache: 'npm'

            # Navigate to the client folder
            - name: Install dependencies for client
              run: |
                  cd client
                  npm ci

            # Build the React project in client folder
            - name: Build React project
              run: |
                  cd client
                  npm run build

            # Setup Pages
            - name: Setup Pages
              uses: actions/configure-pages@v4

            # Upload artifact
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './client/dist'
            
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
